#---
## Ansible Inventory for OpenShift Upgrade Checks
## ==============================================
#
#all:
  #children:
    #openshift_clusters:
      #hosts:
        #localhost:
          #ansible_connection: local
          #ansible_python_interpreter: "/usr/bin/python3"
          #
      #vars:
        ## Override these in group_vars or host_vars
        #cluster_api_url: "https://api.your-cluster.example.com:6443"
        #cluster_token: "{{ vault_openshift_token | default('SET_YOUR_TOKEN_HERE') }}"
        #
        ## Cluster identification
        #cluster_name: "production"
        #cluster_environment: "prod"
        #cluster_region: "us-east-1"
        #
        ## Upgrade configuration
        #mode: "both"  # pre, post, or both
        #fail_on_pre_check_errors: true
        #fail_on_post_check_errors: true
        #
        ## Timing configuration
        #post_upgrade_wait_time: 60
        #health_check_retries: 3
        #health_check_delay: 10
#
# Example multiple cluster setup
# ===============================
# Uncomment and modify for multi-cluster environments

# production_clusters:
#   hosts:
#     prod_east:
#       cluster_api_url: "https://api.prod-east.example.com:6443"
#       cluster_token: "{{ vault_prod_east_token }}"
#       cluster_name: "prod-east"
#       cluster_environment: "production"
#       cluster_region: "us-east-1"
#     prod_west:
#       cluster_api_url: "https://api.prod-west.example.com:6443"
#       cluster_token: "{{ vault_prod_west_token }}"
#       cluster_name: "prod-west"
#       cluster_environment: "production"
#       cluster_region: "us-west-2"

# staging_clusters:
#   hosts:
#     staging:
#       cluster_api_url: "https://api.staging.example.com:6443"
#       cluster_token: "{{ vault_staging_token }}"
#       cluster_name: "staging"
#       cluster_environment: "staging"
#       cluster_region: "us-east-1"
#       fail_on_pre_check_errors: false
#       fail_on_post_check_errors: false

# development_clusters:
#   hosts:
#     dev:
#       cluster_api_url: "https://api.dev.example.com:6443"
#       cluster_token: "{{ vault_dev_token }}"
#       cluster_name: "development"
#       cluster_environment: "dev"
#       cluster_region: "us-east-1"
#       development_mode:
#         enabled: true
